create database customerbehavior;
use customerbehavior;
select*from customer;

#what is the total revenue generated by male and female customers?
select gender,sum(purchase_amount) as revenue from customer group by gender;

#which personn used disc but still spent more than the average purchase amount?
select customer_id,purchase_amount from customer where discount_applied='yes' and purchase_amount>=(select avg(purchase_amount) from customer);

#which are the top 5 products with highest avg review rating?
select item_purchased,avg(review_rating) as "average review rating" from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

#compare the average purchase amounts between standard and express shipping ?
select shipping_type ,avg(purchase_amount) from customer where shipping_type in ('Standard','Express') group by shipping_type;

#Do subsribed customers spend more? compare average spend and total revenue between subscribers and non subscribers?
select subscription_status, count(customer_id)as total_customers, avg(purchase_amount) as avg_spend,sum(purchase_amount) as total_revenue from customer group by subscription_status
order by total_revenue desc ,avg_spend desc;

#which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,round(sum(case when discount_applied='yes' then 1 else 0 end)/count(*)*100,2) as discount_rate from customer
group by item_purchased
order by discount_rate desc
limit 5;

#segment customers into new,returning,and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case
 when previous_purchases=1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal'
end as customer_segment
from customer)
select customer_segment , count(*) as "number of customers" from customer_type
group by customer_segment;

# what are the top 3 most purchased prodducts within each category?
with item_counts as (select item_purchased,category ,count(customer_id)as total_orders,
Row_number() over (partition by category order by count(customer_id)desc) as item_rank from customer group by category,item_purchased)
select item_rank,category,item_purchased,total_orders from item_counts where item_rank<=3;

# customers who are repeat buyers(more than 5 prev purchases)also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers from customer 
where previous_purchases>5
group by subscription_status;

#what is the revenue contribution of each age group?
select age_group,sum(purchase_amount)as total_revenue from customer
group by age_group
order by total_revenue desc;